CREATE TABLE IF NOT EXISTS appointments (
 id SERIAL PRIMARY KEY,
 name VARCHAR(255) NOT NULL,
ail VARCHAR(255),
 phone VARCHAR(30) NOT NULL,
 message TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contact_messages (
 id SERIAL PRIMARY KEY,
 name VARCHAR(255) NOT NULL,
 email VARCHAR(255) NOT NULL,
 subject VARCHAR(255),
 message TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
